name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      entityId:
        description: 'Contentful Entity which is changed'
        required: true
      spaceId:
        description: 'Contentful Space ID'
        required: true
      updatedAt:
        description: 'Date updated'
        required: true

jobs:
  download_and_create_pr:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - run: |
          npm ci
          
      - run: |
          git config --global user.email "nvhoanganh1909@gmail.com"
          git config --global user.name "Anthony (GH Actions)"

      - run: |
          echo "Content ID ${{ github.event.inputs.entityId }} changed in ${{ github.event.inputs.spaceId }}"
          sh create-pr.sh ${{ github.event.inputs.entityId }}
        env:
          ENV: master
          SPACEID: ${{ github.event.inputs.spaceId }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
          ACCESSTOKEN: ${{ secrets.CONTENTFUL_ACCESSTOKEN }}

  push_to_dev:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: TEST
    env:
      SPACEID: ${{ secrets.SPACEID }}
      ACCESSTOKEN: ${{ secrets.CONTENTFUL_ACCESSTOKEN }}
    steps:
      - uses: actions/checkout@v2
  
      - run: |
          npm ci

      - run: |
          ls contents-migrations/
          git diff HEAD~0 --name-only | grep contents-migrations
          git branch 
          git reflog
          sh push-content.sh
        env:
          ENV: dev
          SPACEID: ${{ github.event.inputs.spaceId }}
          ACCESSTOKEN: ${{ secrets.CONTENTFUL_ACCESSTOKEN }}