name: CI

on:
  workflow_dispatch:
    inputs:
      entityId:
        description: 'Contentful Entity which is changed'
        required: true
      spaceId:
        description: 'Contentful Space ID'
        required: true
      updatedAt:
        description: 'Date updated'
        required: true

jobs:
  download_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - run: |
          echo "Content ID ${{ github.event.inputs.entityId }} changed in ${{ github.event.inputs.spaceId }}"
          echo "Check using $ACCESSTOKEN and $GITHUB_TOKEN"
          gh pr list
        env:
          ENV: master
          SPACEID: ${{ secrets.SPACEID }} 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
          ACCESSTOKEN: ${{ secrets.CONTENTFUL_ACCESSTOKEN }}