name: CI

on:
  workflow_dispatch:
    inputs:
      entityId:
        description: 'Contentful Entity which is changed'
        required: true
      spaceId:
        description: 'Contentful Space ID'
        required: true
      updatedAt:
        description: 'Date updated'
        required: true

jobs:
  download_and_create_pr:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Content ID ${{ github.event.inputs.entityId }} changed in ${{ github.event.inputs.spaceId }}"
